name: game_addiction
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.1
  go_router: ^5.2.0
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  rive: ^0.9.1
  fl_chart: ^0.55.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  after_layout: ^1.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#9D55EA"
  image: assets/images/splash.png
  color_dark: "#0C0B10"
  image_dark: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#AE94F9"
    icon_background_color: "#EEEEEE"
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/rives/

  fonts:
    - family: yeseva
      fonts:
        - asset: assets/fonts/yeseva.ttf

    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/quicksand/static/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand/static/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/quicksand/static/Quicksand-Bold.ttf
          weight: 700

  